/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module nand_gate(a, b, y);
  wire _0_;
  wire _1_;
  wire _2_;
  input a;
  wire a;
  input b;
  wire b;
  output y;
  wire y;
  assign _2_ = 4'h7 >> { _0_, _1_ };
  assign _1_ = b;
  assign _0_ = a;
  assign y = _2_;
endmodule
